feat: exit if a failure is found

diff --git a/check-jobs-status/action.yml b/check-jobs-status/action.yml
--- a/check-jobs-status/action.yml
+++ b/check-jobs-status/action.yml
@@ -13,9 +13,12 @@ runs:
       id: print_needs
       shell: bash
       run: |
-        echo "${{ inputs.jobs }}"
         for job_name in $(echo '${{ inputs.jobs }}' | jq -r 'keys[]'); do
-          echo "$job_name"
           result=$(echo '${{ inputs.jobs }}' | jq -r ".[\"$job_name\"].result")
-          echo "Result: $result"
+          if [[ "$result" == "failure" ]]; then
+            echo "$job_name failed!"
+            exit 1
         done
+
+        echo "All jobs were successful!"
+        exit 0
