feat: check jobs

diff --git a/check-jobs-status/action.yml b/check-jobs-status/action.yml
--- a/check-jobs-status/action.yml
+++ b/check-jobs-status/action.yml
@@ -13,7 +13,13 @@ runs:
       id: print_needs
       shell: bash
       run: |
-        echo "==="
         job_needs=${{ fromJson(inputs.jobs) }}
-        echo "$job_needs"
-        echo "==="
+        for job in "${jobs_needs[@]}"; do
+          job_status=$(echo "${{ inputs.jobs.${job}.outputs.status }}" | tr -d '"')
+          if [ "$job_status" != "success" ]; then
+            echo "Job $job failed or has not completed successfully."
+            exit 1
+          fi
+        done
+
+        echo "All previous jobs are successful."
